services:
  correspondence:
    build: ./correspondence
    environment:
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=efolder
    ports: ["8085:8085"]
    depends_on: [ minio ]
